"""initial_tables

Revision ID: b56d8078b1a8
Revises: 
Create Date: 2026-03-08 03:04:35.324175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b56d8078b1a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ruc', sa.String(length=13), nullable=False),
    sa.Column('sri_usuario_enc', sa.Text(), nullable=False),
    sa.Column('sri_password_enc', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_ruc'), 'tenants', ['ruc'], unique=True)
    op.create_table('comprobantes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('estado_autorizacion', sa.String(length=20), nullable=False),
    sa.Column('numero_autorizacion', sa.String(length=49), nullable=False),
    sa.Column('fecha_autorizacion', sa.DateTime(), nullable=True),
    sa.Column('ambiente_autorizacion', sa.String(length=20), nullable=False),
    sa.Column('ruc_emisor', sa.String(length=13), nullable=False),
    sa.Column('razon_social_emisor', sa.String(length=300), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=300), nullable=True),
    sa.Column('cod_doc', sa.String(length=2), nullable=False),
    sa.Column('tipo_comprobante', sa.Enum('FACTURA', 'LIQUIDACION', 'NOTA_CREDITO', 'NOTA_DEBITO', 'RETENCION', 'GUIA_REMISION', name='tipocomprobante'), nullable=False),
    sa.Column('clave_acceso', sa.String(length=49), nullable=False),
    sa.Column('estab', sa.String(length=3), nullable=False),
    sa.Column('pto_emi', sa.String(length=3), nullable=False),
    sa.Column('secuencial', sa.String(length=9), nullable=False),
    sa.Column('serie', sa.String(length=7), nullable=False),
    sa.Column('numero_completo', sa.String(length=17), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('dir_establecimiento', sa.Text(), nullable=True),
    sa.Column('obligado_contabilidad', sa.String(length=2), nullable=True),
    sa.Column('contribuyente_especial', sa.String(length=10), nullable=True),
    sa.Column('tipo_id_receptor', sa.String(length=2), nullable=True),
    sa.Column('razon_social_receptor', sa.String(length=300), nullable=True),
    sa.Column('identificacion_receptor', sa.String(length=13), nullable=True),
    sa.Column('periodo_fiscal', sa.String(length=7), nullable=True),
    sa.Column('total_sin_impuestos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_descuento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('importe_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('propina', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('xml_raw', sa.Text(), nullable=False),
    sa.Column('xml_path', sa.String(length=500), nullable=True),
    sa.Column('parse_error', sa.Boolean(), nullable=False),
    sa.Column('parse_error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'clave_acceso')
    )
    op.create_index('ix_comp_tenant_fecha', 'comprobantes', ['tenant_id', 'fecha_emision'], unique=False)
    op.create_index(op.f('ix_comprobantes_clave_acceso'), 'comprobantes', ['clave_acceso'], unique=False)
    op.create_index(op.f('ix_comprobantes_fecha_emision'), 'comprobantes', ['fecha_emision'], unique=False)
    op.create_index(op.f('ix_comprobantes_ruc_emisor'), 'comprobantes', ['ruc_emisor'], unique=False)
    op.create_index(op.f('ix_comprobantes_tenant_id'), 'comprobantes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_comprobantes_tipo_comprobante'), 'comprobantes', ['tipo_comprobante'], unique=False)
    op.create_table('ejecuciones_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('periodo_anio', sa.Integer(), nullable=False),
    sa.Column('periodo_mes', sa.Integer(), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.Enum('INICIADO', 'EN_PROGRESO', 'COMPLETADO', 'ERROR', 'CAPTCHA_BLOQUEADO', 'SRI_MANTENIMIENTO', name='estadoejecucion'), nullable=False),
    sa.Column('total_encontrados', sa.Integer(), nullable=False),
    sa.Column('total_nuevos', sa.Integer(), nullable=False),
    sa.Column('total_errores', sa.Integer(), nullable=False),
    sa.Column('duracion_seg', sa.Float(), nullable=True),
    sa.Column('error_mensaje', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('pagina_actual', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejecuciones_log_estado'), 'ejecuciones_log', ['estado'], unique=False)
    op.create_index(op.f('ix_ejecuciones_log_tenant_id'), 'ejecuciones_log', ['tenant_id'], unique=False)
    op.create_table('detalles_comprobante',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comprobante_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('codigo_principal', sa.String(length=50), nullable=True),
    sa.Column('codigo_auxiliar', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('precio_total_sin_impuesto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva_codigo', sa.String(length=2), nullable=True),
    sa.Column('iva_codigo_porcentaje', sa.String(length=2), nullable=True),
    sa.Column('iva_tarifa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('iva_base_imponible', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva_valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_comprobante_comprobante_id'), 'detalles_comprobante', ['comprobante_id'], unique=False)
    op.create_table('impuestos_retencion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comprobante_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=1), nullable=False),
    sa.Column('tipo_tributo', sa.Enum('RENTA', 'IVA', 'ISD', name='tipotributo'), nullable=False),
    sa.Column('codigo_retencion', sa.String(length=10), nullable=False),
    sa.Column('base_imponible', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('porcentaje_retener', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valor_retenido', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cod_doc_sustento', sa.String(length=2), nullable=True),
    sa.Column('num_doc_sustento', sa.String(length=17), nullable=True),
    sa.Column('fecha_emision_doc_sustento', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impuestos_retencion_comprobante_id'), 'impuestos_retencion', ['comprobante_id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comprobante_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('forma_pago', sa.String(length=2), nullable=False),
    sa.Column('forma_pago_desc', sa.String(length=100), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('plazo', sa.String(length=10), nullable=True),
    sa.Column('unidad_tiempo', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_comprobante_id'), 'pagos', ['comprobante_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_comprobante_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_impuestos_retencion_comprobante_id'), table_name='impuestos_retencion')
    op.drop_table('impuestos_retencion')
    op.drop_index(op.f('ix_detalles_comprobante_comprobante_id'), table_name='detalles_comprobante')
    op.drop_table('detalles_comprobante')
    op.drop_index(op.f('ix_ejecuciones_log_tenant_id'), table_name='ejecuciones_log')
    op.drop_index(op.f('ix_ejecuciones_log_estado'), table_name='ejecuciones_log')
    op.drop_table('ejecuciones_log')
    op.drop_index(op.f('ix_comprobantes_tipo_comprobante'), table_name='comprobantes')
    op.drop_index(op.f('ix_comprobantes_tenant_id'), table_name='comprobantes')
    op.drop_index(op.f('ix_comprobantes_ruc_emisor'), table_name='comprobantes')
    op.drop_index(op.f('ix_comprobantes_fecha_emision'), table_name='comprobantes')
    op.drop_index(op.f('ix_comprobantes_clave_acceso'), table_name='comprobantes')
    op.drop_index('ix_comp_tenant_fecha', table_name='comprobantes')
    op.drop_table('comprobantes')
    op.drop_index(op.f('ix_tenants_ruc'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
