#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-${ROOT_DIR}/.env.vps}"
FORCE_RECREATE_ENV="${FORCE_RECREATE_ENV:-false}"

random_hex() {
  local bytes="${1}"
  od -An -N "${bytes}" -tx1 /dev/urandom | tr -d ' \n'
}

if [[ -s "${ENV_FILE}" && "${FORCE_RECREATE_ENV}" != "true" ]]; then
  echo "El archivo ya existe: ${ENV_FILE}"
  exit 0
fi

mkdir -p "$(dirname "${ENV_FILE}")"

POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(random_hex 24)}"
SECRET_KEY="${SECRET_KEY:-$(random_hex 32)}"

cat > "${ENV_FILE}" <<EOF
API_DOMAIN=${API_DOMAIN:-sri-process.amephia.com}

# Seguridad
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
SECRET_KEY=${SECRET_KEY}

# API / workers
API_WORKERS=${API_WORKERS:-2}
CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-3}
CELERY_LOGLEVEL=${CELERY_LOGLEVEL:-info}

# CAPTCHA
CAPTCHA_PROVIDER=${CAPTCHA_PROVIDER:-capsolver}
TWOCAPTCHA_API_KEY=${TWOCAPTCHA_API_KEY:-}
CAPSOLVER_API_KEY=${CAPSOLVER_API_KEY:-}
CAPTCHA_ASSISTED_MODE=${CAPTCHA_ASSISTED_MODE:-off}
CAPTCHA_ASSISTED_TIMEOUT_SEC=${CAPTCHA_ASSISTED_TIMEOUT_SEC:-180}
RECAPTCHA_SITEKEY_FALLBACK=${RECAPTCHA_SITEKEY_FALLBACK:-}

# Browser
BROWSER_PREFER_NODRIVER=${BROWSER_PREFER_NODRIVER:-true}
BROWSER_PERSISTENT_CONTEXT=${BROWSER_PERSISTENT_CONTEXT:-true}
BROWSER_EXECUTABLE_PATH=${BROWSER_EXECUTABLE_PATH:-}
BROWSER_CHANNEL=${BROWSER_CHANNEL:-}
BROWSER_PROXY_SERVER=${BROWSER_PROXY_SERVER:-}
BROWSER_PROXY_USERNAME=${BROWSER_PROXY_USERNAME:-}
BROWSER_PROXY_PASSWORD=${BROWSER_PROXY_PASSWORD:-}
BROWSER_PROXY_BYPASS=${BROWSER_PROXY_BYPASS:-}
BROWSER_TIMEOUT_MS=${BROWSER_TIMEOUT_MS:-30000}
DOWNLOAD_TIMEOUT_MS=${DOWNLOAD_TIMEOUT_MS:-45000}

# Anti-deteccion
DELAY_MIN_MS=${DELAY_MIN_MS:-800}
DELAY_MAX_MS=${DELAY_MAX_MS:-2500}
DELAY_BETWEEN_PAGES_MS=${DELAY_BETWEEN_PAGES_MS:-2000}

# Retries
MAX_RETRIES=${MAX_RETRIES:-5}
RETRY_WAIT_MIN_SEC=${RETRY_WAIT_MIN_SEC:-4}
RETRY_WAIT_MAX_SEC=${RETRY_WAIT_MAX_SEC:-300}
CIRCUIT_BREAKER_THRESHOLD=${CIRCUIT_BREAKER_THRESHOLD:-5}
CIRCUIT_BREAKER_TIMEOUT_MIN=${CIRCUIT_BREAKER_TIMEOUT_MIN:-30}

# Concurrencia / DB pool
MAX_CONCURRENT_TENANTS=${MAX_CONCURRENT_TENANTS:-3}
BROWSER_POOL_LIMIT=${BROWSER_POOL_LIMIT:-3}
DATABASE_POOL_SIZE=${DATABASE_POOL_SIZE:-10}
DATABASE_MAX_OVERFLOW=${DATABASE_MAX_OVERFLOW:-20}

# Storage dentro del contenedor
XML_STORAGE_PATH=${XML_STORAGE_PATH:-/app/xmls}
SCREENSHOT_PATH=${SCREENSHOT_PATH:-/app/screenshots}
SCREENSHOT_ON_ERROR=${SCREENSHOT_ON_ERROR:-true}
BROWSER_PROFILE_PATH=${BROWSER_PROFILE_PATH:-/app/chrome_profile}

# Scheduler (hora Ecuador UTC-5)
SCHEDULE_HOUR=${SCHEDULE_HOUR:-6}
SCHEDULE_MINUTE=${SCHEDULE_MINUTE:-30}

# Notificaciones opcionales
SMTP_HOST=${SMTP_HOST:-}
SMTP_PORT=${SMTP_PORT:-587}
SMTP_USER=${SMTP_USER:-}
SMTP_PASS=${SMTP_PASS:-}
ALERT_EMAIL=${ALERT_EMAIL:-}

# Observabilidad opcional
SENTRY_DSN=${SENTRY_DSN:-}
EOF

echo "Archivo generado automáticamente: ${ENV_FILE}"
echo "API_DOMAIN=$(grep '^API_DOMAIN=' "${ENV_FILE}" | cut -d= -f2-)"
